'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class manage_request

    '''<summary>
    '''fYear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fYear As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''fStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fStatus As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''fuser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuser As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''RequestsTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RequestsTable As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''viewTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents viewTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''principalData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents principalData As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''technicalInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents technicalInformation As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''requestData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents requestData As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''filesData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filesData As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''userData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userData As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''assignAginLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents assignAginLabel As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''assignTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents assignTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''users control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents users As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''descriptionAssign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descriptionAssign As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''assign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents assign As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''addDetailTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents addDetailTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''adminPermission control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminPermission As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''daysLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents daysLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''days control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents days As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''updateAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents updateAdmin As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''noReq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents noReq As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''operativeUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents operativeUnit As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''receive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents receive As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''clarification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clarification As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''extension control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents extension As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''extensionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents extensionLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''extensionJustification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents extensionJustification As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''review control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents review As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''affirmative control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents affirmative As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox

    '''<summary>
    '''resolution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resolution As Global.System.Web.UI.HtmlControls.HtmlInputGenericControl

    '''<summary>
    '''delivery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents delivery As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''oficioTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oficioTable As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''sendmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sendmail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''add_detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents add_detail As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''modalEditOficioTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents modalEditOficioTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''newOficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newOficio As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''newOperativeUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newOperativeUnit As Global.System.Web.UI.HtmlControls.HtmlSelect

    '''<summary>
    '''editOficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents editOficio As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''deleteOficio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deleteOficio As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''replyTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents replyTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''files control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents files As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''descriptionReply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents descriptionReply As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''notApply control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents notApply As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''replyReuqest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents replyReuqest As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
